PATH:
  DATA: "D:/devel/MoraiLauncher_Win/MoraiLauncher_Win/MoraiLauncher_Win_Data/SaveFile/SensorData"
  SAVE: "./models"
MODEL:
  SAVE_MODEL: True
  MODEL_NAME: "seongnam_cityhall.pcd" # file name
  VOXEL_SIZE: 0.5 # downsampling
VISUALIZE:
  ACTIVE_VIS: True
  FINAL_VIS: True
  SAMPLE_VIS: False # ONLY turn on when you need to test a sample # sample size is 5 
LIDAR:
  DUAL: False 
  NOISE: 0
  THRES: True
  RANGE: [3, 70] # [min(m), max(m)]
LIDAR1:
  PATH: "LIDAR_2"
  TRANSFORM: [0, 0, 2.5, 0, 0, 0] # [x, y, z, roll, pitch, yaw] #[m, m, m, deg, deg, deg]
LIDAR2:
  PATH: "LIDAR_4"
  TRANSFORM: [0, 0, 0, 0, 0, 0] # [x, y, z, roll, pitch, yaw] #[m, m, m, deg, deg, deg]
IMU:
  PATH: "IMU_1"
GPS:
  PATH: "GPS_3"
