PATH:
  DATA: "D:/MoraiLauncher_Win (1)/MoraiLauncher_Win/MoraiLauncher_Win_Data/SaveFile/SensorData" #"D:/MoraiLauncher_Win/MoraiLauncher_Win/MoraiLauncher_Win_Data/SaveFile/SensorData"
  SAVE: "./models"
MODEL:
  SAVE_MODEL: True
  MODEL_NAME: "seongnam_cityhall.pcd" # file name
  VOXEL_SIZE: 0.5 # downsampling
VISUALIZE:
  ACTIVE_VIS: True
  FINAL_VIS: True
LIDAR:
  DUAL: True
  NOISE: 0
  THRES: True
  RANGE: [3, 70]
LIDAR1:
  PATH: "LIDAR_1"
  TRANSFORM: [1.3, 1, 1.6, -30, 0, 0] # [x, y, z, roll, pitch, yaw]
LIDAR2:
  PATH: "LIDAR_4"
  TRANSFORM: [1.3, -1, 1.6, -330, 0, 0] # [x, y, z, roll, pitch, yaw]
IMU:
  PATH: "IMU_3"
GPS:
  PATH: "GPS_2"


# "D:/MoraiLauncher_Win (1)/MoraiLauncher_Win/MoraiLauncher_Win_Data/SaveFile/SensorData"